name: CI

on:
  push:
    branches: [main]

jobs:
  ci:
    name: Lint, Test, Build
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build
